# Generated by Django 6.0.3 on 2026-03-06 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='services.service')),
            ],
            options={
                'db_table': 'service_stages',
                'ordering': ['service', 'stage_order'],
                'unique_together': {('service', 'stage_name'), ('service', 'stage_order')},
            },
        ),
    ]
