# Generated by Django 6.0.3 on 2026-03-06 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_mins', models.PositiveIntegerField(default=60)),
                ('total_capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='airports.airport')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('airport', 'date', 'start_time')},
            },
        ),
    ]
