# Generated by Django 6.0.3 on 2026-03-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='e.g. Asia/Kolkata, America/New_York', max_length=50),
        ),
    ]
