# Generated by Django 6.0.3 on 2026-03-06 13:04

import apps.operations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.CharField(default=apps.operations.models.generate_job_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quality_score', models.PositiveIntegerField(blank=True, help_text='1 to 5', null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='airports.airport')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_card', to='bookings.booking')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(choices=[('received', 'Received'), ('pre_inspection', 'Pre Inspection'), ('washing', 'Washing'), ('drying', 'Drying'), ('detailing', 'Detailing'), ('quality_check', 'Quality Check'), ('ready', 'Ready for Pickup')], max_length=20)),
                ('stage_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='operations.jobcard')),
            ],
            options={
                'db_table': 'work_stages',
                'ordering': ['job_card', 'stage_order'],
                'unique_together': {('job_card', 'stage_name')},
            },
        ),
    ]
