# Generated by Django 6.0.3 on 2026-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstage',
            name='stage_name',
            field=models.CharField(max_length=100),
        ),
    ]
