# Generated by Django 6.0.3 on 2026-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_workstage_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='total_estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workstage',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
