# Generated by Django 6.0.3 on 2026-03-06 13:04

import apps.bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        ('parking', '0001_initial'),
        ('services', '0001_initial'),
        ('slots', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(default=apps.bookings.models.generate_booking_reference, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_stage', models.CharField(blank=True, choices=[('received', 'Received'), ('inspection', 'Pre Inspection'), ('washing', 'Washing'), ('drying', 'Drying'), ('detailing', 'Detailing'), ('qc', 'Quality Check'), ('ready', 'Ready for Pickup')], max_length=20, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airports.airport')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('parking_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_booking', to='parking.parkingbooking')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slots.timeslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='services.service')),
            ],
            options={
                'db_table': 'booking_items',
            },
        ),
    ]
