# Generated by Django 6.0.3 on 2026-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('pre_inspection', 'Pre Inspection'), ('washing', 'Washing'), ('drying', 'Drying'), ('detailing', 'Detailing'), ('quality_check', 'Quality Check'), ('ready', 'Ready for Pickup')], max_length=20, null=True),
        ),
    ]
