# Generated by Django 6.0.3 on 2026-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
