# Generated by Django 6.0.3 on 2026-03-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatroom_airport"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="chat.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("work_started", "Work Started"),
                    ("stage_complete", "Stage Completed"),
                    ("car_ready", "Car Ready for Pickup"),
                    ("payment_due", "Payment Due"),
                    ("chat_message", "New Chat Message"),
                    ("new_booking", "New Booking Received"),
                ],
                max_length=30,
            ),
        ),
    ]
